version: '3'

services:
    api:
        build:
            context: .
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - .env.dev
    database:
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./database-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: propel
            POSTGRES_DB: propel
            POSTGRES_USER: propel

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U propel -d propel"]
            interval: 10s
            timeout: 10s
            retries: 5