
services:
    database:
        image: postgres:13
        restart: always
        # ports:
        #     - "5432:5432"
        volumes:
            - ./database-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: propel
            POSTGRES_DB: propel
            POSTGRES_USER: propel

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U propel -d propel"]
            interval: 10s
            timeout: 10s
            retries: 5
    api:
        build:
            context: .
        restart: always
        ports:
            - "8008:8008"
        depends_on:
            - database
        env_file:
            - .env
    
    # nginx:
    #     image: nginx:latest
    #     restart: always
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     depends_on:
    #         - api